version: "3.1"
services:
 frontend:
    build: ./client/frontend
    container_name: frontend_container
    volumes:
      - "./client/frontend:/client/frontend"
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api

 api:
    build: ./server
    container_name: api_container
    volumes:
      - "./server:/server"
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      DB_CONNECTION_STRING: postgres://postgres:docker@db:5432/movielist
    depends_on:
      - db

 db:
    image: postgres:latest
    container_name: db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: movielist
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network

networks:
 app-network:
    driver: bridge